/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * PAYMENT API
 * OpenAPI spec version: 0.0.1
 */

/**
 * Transaction status
 */
export type PaymentHistoryResponseStatus = typeof PaymentHistoryResponseStatus[keyof typeof PaymentHistoryResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentHistoryResponseStatus = {
  PENDING: 'PENDING',
  WAITING_FOR_CAPTURE: 'WAITING_FOR_CAPTURE',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
} as const;
